"""Generated ``WORK.md`` board: a human- and agent-readable Work Graph mirror.

The Work Graph is authoritative JSONL under ``.agentflow/work/`` — precise, but
invisible to an agent doing ordinary context gathering (reading the files a repo
puts in front of it). ``WORK.md`` closes that gap: a deterministically generated
Markdown board, written at the repository root, that renders the open and
proposed Work Items with their acceptance criteria and the claim-and-propose
protocol every agent should follow.

The mirror is *generated*, never authored. It is regenerated by every
graph-mutating write (``save_work_graph``, and therefore every command that
reaches ``.agentflow/work/``), and regeneration is a pure function of the graph
content, so an already-current mirror re-renders to the identical bytes and
produces no diff. The board deliberately lives outside ``.agentflow/work/`` so it
is never parsed as Work Graph content or folded into the graph content hash —
the same reasoning that keeps the approval mirror out of that directory.

Rendering never reads Run Evidence or Agentflow Home: "open" here means a Work
Item that is not a ``proposed`` Discovery/proposal awaiting Framing (the same
open/proposed split ``compute_ready_work`` and ``items_touching`` use), so the
board is a pure projection of the graph the write just persisted.
"""

from __future__ import annotations

from pathlib import Path

from .contracts import WORK_ITEM_STATUS_PROPOSED

WORK_MD_FILENAME = "WORK.md"

_GENERATED_MARKER = (
    "<!-- GENERATED by `agentflow` from .agentflow/work/ — DO NOT EDIT. "
    "Edits are overwritten on the next graph-mutating command. -->"
)

_PREAMBLE = (
    "This board is a generated mirror of the authoritative Work Graph under "
    "`.agentflow/work/`. It is regenerated by every graph-mutating Agentflow "
    "command; hand edits here are overwritten and change nothing. To change the "
    "work itself, edit the Work Graph through Agentflow or drop a proposal — "
    "never edit this file."
)

_PROTOCOL = (
    "## How to claim and propose work\n"
    "\n"
    "- **Consult this board before starting.** Pick the open Work Item you "
    "intend to deliver from the list below.\n"
    "- **Carry the Work-Item id in your commits.** Add a `Work-Item: <id>` "
    "trailer so the work you land is matched to its open item.\n"
    "- **Propose first for uncovered work.** If what you need to do is not an "
    "open item, drop a JSON proposal into `.agentflow/proposals/`; a human "
    "ingests proposals into the graph during Framing. Proposed items below are "
    "awaiting that review and are not yet claimable.\n"
    "- **Never edit `.agentflow/work/` directly.** The Work Graph is mutated "
    "only through Agentflow; direct edits are rejected.\n"
)


def _escape_markdown(text: str) -> str:
    """Neutralize leading Markdown heading syntax in free-form Work Item text.

    A Work Item's ``summary`` and acceptance criteria are free-form and are not
    trusted as layout: a value beginning a line with ``#`` must not be able to
    open a section heading and spoof the open/proposed structure the board
    exists to make legible. Escaping every leading ``#`` on a line renders the
    text verbatim (Markdown shows the literal ``#``) while breaking the raw
    heading substring anything scanning ``WORK.md`` by heading text keys on.
    """
    escaped_lines = []
    for line in text.split("\n"):
        stripped = line.lstrip()
        indent = line[: len(line) - len(stripped)]
        hashes = len(stripped) - len(stripped.lstrip("#"))
        if hashes:
            escaped_lines.append(indent + "\\#" * hashes + stripped[hashes:])
        else:
            escaped_lines.append(line)
    return "\n".join(escaped_lines)


def _render_item(item: dict) -> str:
    """Render one Work Item as a Markdown section, deterministically."""
    lines = [f"### {_escape_markdown(item['id'])}", "", _escape_markdown(item["summary"]), ""]
    depends_on = item.get("depends_on") or []
    if depends_on:
        lines.append("Depends on: " + ", ".join(_escape_markdown(dep) for dep in depends_on))
    else:
        lines.append("Depends on: nothing")
    files = item.get("files") or []
    if files:
        lines.append("File scope: " + ", ".join(_escape_markdown(glob) for glob in files))
    criteria = item.get("acceptance_criteria") or []
    lines.append("")
    if criteria:
        lines.append("Acceptance criteria:")
        lines.extend(f"- {_escape_markdown(criterion)}" for criterion in criteria)
    else:
        lines.append("Acceptance criteria: _none recorded._")
    return "\n".join(lines)


def _render_section(title: str, items: list[dict]) -> str:
    """Render a titled section of Work Items, preserving graph order."""
    if not items:
        return f"## {title}\n\n_None._\n"
    body = "\n\n".join(_render_item(item) for item in items)
    return f"## {title}\n\n{body}\n"


def render_work_md(items: list[dict]) -> str:
    """Render the ``WORK.md`` board for a Work Graph, deterministically.

    Pure function of the graph content: the same items always render to the
    same bytes, so a current mirror re-renders identically and produces no diff.
    Items are split into open (belonging to the approved graph) and proposed
    (appended from a Discovery or proposal, awaiting human Framing), matching the
    open/proposed distinction used across the Work Graph, and each section
    preserves the graph's order.
    """
    open_items = [
        item for item in items
        if item.get("status") != WORK_ITEM_STATUS_PROPOSED
    ]
    proposed_items = [
        item for item in items
        if item.get("status") == WORK_ITEM_STATUS_PROPOSED
    ]
    parts = [
        _GENERATED_MARKER,
        "",
        "# Work Board",
        "",
        _PREAMBLE,
        "",
        _PROTOCOL,
        "",
        _render_section("Open Work Items", open_items),
        "",
        _render_section("Proposed Work Items", proposed_items),
    ]
    return "\n".join(parts).rstrip("\n") + "\n"


def work_md_path(repository: Path) -> Path:
    """Path of the generated board mirror at the repository root."""
    return Path(repository) / WORK_MD_FILENAME


def write_work_md(repository: Path, items: list[dict]) -> Path:
    """Regenerate the ``WORK.md`` mirror for ``repository`` from ``items``.

    Writes the rendered board to the repository root and returns its path.
    Idempotent: re-running with the same graph writes identical bytes, so an
    up-to-date mirror produces no diff. This is the only writer of the mirror;
    it is called from ``save_work_graph`` so every graph mutation refreshes it.
    """
    path = work_md_path(repository)
    path.write_text(render_work_md(items), encoding="utf-8")
    return path
